# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Proj\Main\borrow1.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_borrow1(object):
    def setupUi(self, borrow1):
        borrow1.setObjectName("borrow1")
        borrow1.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(borrow1)
        self.centralwidget.setObjectName("centralwidget")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(190, 10, 411, 111))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_7.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("AR BONNIE")
        font.setPointSize(20)
        font.setUnderline(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(130, 230, 101, 23))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_6 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_6.setGeometry(QtCore.QRect(130, 350, 141, 23))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_5.setGeometry(QtCore.QRect(130, 320, 141, 23))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(130, 200, 101, 23))
        self.checkBox.setObjectName("checkBox")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(290, 290, 41, 25))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(280, 420, 112, 34))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(290, 230, 41, 25))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(130, 290, 141, 23))
        self.checkBox_4.setObjectName("checkBox_4")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_12.setGeometry(QtCore.QRect(290, 170, 41, 25))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 130, 68, 19))
        self.label.setObjectName("label")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(290, 200, 41, 25))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_10.setGeometry(QtCore.QRect(290, 350, 41, 25))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_11.setGeometry(QtCore.QRect(290, 320, 41, 25))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.checkBox_7 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_7.setGeometry(QtCore.QRect(130, 170, 101, 23))
        self.checkBox_7.setObjectName("checkBox_7")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 140, 68, 19))
        self.label_2.setObjectName("label_2")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(290, 260, 41, 25))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(130, 260, 141, 23))
        self.checkBox_3.setObjectName("checkBox_3")
        borrow1.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(borrow1)
        self.statusbar.setObjectName("statusbar")
        borrow1.setStatusBar(self.statusbar)

        self.retranslateUi(borrow1)
        QtCore.QMetaObject.connectSlotsByName(borrow1)

    def retranslateUi(self, borrow1):
        _translate = QtCore.QCoreApplication.translate
        borrow1.setWindowTitle(_translate("borrow1", "MainWindow"))
        self.label_7.setText(_translate("borrow1", "CISCO BORROWING SYSTEM "))
        self.checkBox_2.setText(_translate("borrow1", "Router"))
        self.checkBox_6.setText(_translate("borrow1", "LAN Cable"))
        self.checkBox_5.setText(_translate("borrow1", "Power Cable"))
        self.checkBox.setText(_translate("borrow1", "Switch"))
        self.pushButton.setText(_translate("borrow1", "Borrow"))
        self.checkBox_4.setText(_translate("borrow1", "LAN Cable"))
        self.label.setText(_translate("borrow1", "Quantity"))
        self.checkBox_7.setText(_translate("borrow1", "Rack"))
        self.label_2.setText(_translate("borrow1", "Item"))
        self.checkBox_3.setText(_translate("borrow1", "Console Cable"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    borrow1 = QtWidgets.QMainWindow()
    ui = Ui_borrow1()
    ui.setupUi(borrow1)
    borrow1.show()
    sys.exit(app.exec_())

