# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Rachel Abbie Fernand\Documents\1Q1819\COE125\Copy\Borrow1.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import Borrow
import sqlite3
    
class Ui_BorrowForm1(object):
    av0 = 0
    av1 = 0
    av2 = 0
    av3 = 0
    av4 = 0
    av5 = 0
    
    def setupUi(self, BorrowForm1):
        BorrowForm1.setObjectName("BorrowForm1")
        BorrowForm1.resize(802, 600)
        self.centralwidget = QtWidgets.QWidget(BorrowForm1)
        self.centralwidget.setObjectName("centralwidget")
        self.borrowbtn = QtWidgets.QPushButton(self.centralwidget)
        self.borrowbtn.setGeometry(QtCore.QRect(490, 480, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.borrowbtn.setFont(font)
        self.borrowbtn.setObjectName("borrowbtn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(510, 240, 131, 19))
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 351, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_7.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("AR BONNIE")
        font.setPointSize(20)
        font.setUnderline(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 240, 68, 19))
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 40, 251, 81))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_8.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(20)
        font.setUnderline(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.cb0 = QtWidgets.QCheckBox(self.centralwidget)
        self.cb0.setGeometry(QtCore.QRect(220, 280, 101, 23))
        self.cb0.setObjectName("cb0")
        self.l0 = QtWidgets.QLineEdit(self.centralwidget)
        self.l0.setGeometry(QtCore.QRect(530, 280, 51, 25))
        self.l0.setObjectName("l0")
        self.cb1 = QtWidgets.QCheckBox(self.centralwidget)
        self.cb1.setGeometry(QtCore.QRect(220, 310, 101, 23))
        self.cb1.setObjectName("cb1")
        self.l1 = QtWidgets.QLineEdit(self.centralwidget)
        self.l1.setGeometry(QtCore.QRect(530, 310, 51, 25))
        self.l1.setObjectName("l1")
        self.cb2 = QtWidgets.QCheckBox(self.centralwidget)
        self.cb2.setGeometry(QtCore.QRect(220, 340, 101, 23))
        self.cb2.setObjectName("cb2")
        self.l2 = QtWidgets.QLineEdit(self.centralwidget)
        self.l2.setGeometry(QtCore.QRect(530, 340, 51, 25))
        self.l2.setObjectName("l2")
        self.cb3 = QtWidgets.QCheckBox(self.centralwidget)
        self.cb3.setGeometry(QtCore.QRect(220, 370, 141, 23))
        self.cb3.setObjectName("cb3")
        self.l3 = QtWidgets.QLineEdit(self.centralwidget)
        self.l3.setGeometry(QtCore.QRect(530, 370, 51, 25))
        self.l3.setObjectName("l3")
        self.cb4 = QtWidgets.QCheckBox(self.centralwidget)
        self.cb4.setGeometry(QtCore.QRect(220, 400, 121, 23))
        self.cb4.setObjectName("cb4")
        self.l4 = QtWidgets.QLineEdit(self.centralwidget)
        self.l4.setGeometry(QtCore.QRect(530, 400, 51, 25))
        self.l4.setObjectName("l4")
        self.cb5 = QtWidgets.QCheckBox(self.centralwidget)
        self.cb5.setGeometry(QtCore.QRect(220, 430, 121, 23))
        self.cb5.setObjectName("cb5")
        self.l5 = QtWidgets.QLineEdit(self.centralwidget)
        self.l5.setGeometry(QtCore.QRect(530, 430, 51, 25))
        self.l5.setObjectName("l5")
        self.labelName = QtWidgets.QLabel(self.centralwidget)
        self.labelName.setGeometry(QtCore.QRect(30, 130, 68, 19))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelName.setFont(font)
        self.labelName.setObjectName("labelName")
        self.labelStudNum = QtWidgets.QLabel(self.centralwidget)
        self.labelStudNum.setGeometry(QtCore.QRect(30, 160, 131, 19))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelStudNum.setFont(font)
        self.labelStudNum.setObjectName("labelStudNum")
        self.labelSection = QtWidgets.QLabel(self.centralwidget)
        self.labelSection.setGeometry(QtCore.QRect(370, 130, 131, 19))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelSection.setFont(font)
        self.labelSection.setObjectName("labelSection")
        self.labelRoom = QtWidgets.QLabel(self.centralwidget)
        self.labelRoom.setGeometry(QtCore.QRect(370, 160, 131, 19))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelRoom.setFont(font)
        self.labelRoom.setObjectName("labelRoom")
        self.labelRoom_2 = QtWidgets.QLabel(self.centralwidget)
        self.labelRoom_2.setGeometry(QtCore.QRect(550, 130, 131, 19))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelRoom_2.setFont(font)
        self.labelRoom_2.setObjectName("labelRoom_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(340, 240, 131, 19))
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.a0 = QtWidgets.QLabel(self.centralwidget)
        self.a0.setGeometry(QtCore.QRect(380, 280, 68, 19))
        self.a0.setObjectName("a0")
        self.a1 = QtWidgets.QLabel(self.centralwidget)
        self.a1.setGeometry(QtCore.QRect(380, 310, 68, 19))
        self.a1.setObjectName("a1")
        self.a2 = QtWidgets.QLabel(self.centralwidget)
        self.a2.setGeometry(QtCore.QRect(380, 340, 68, 19))
        self.a2.setObjectName("a2")
        self.a3 = QtWidgets.QLabel(self.centralwidget)
        self.a3.setGeometry(QtCore.QRect(380, 370, 68, 19))
        self.a3.setObjectName("a3")
        self.a4 = QtWidgets.QLabel(self.centralwidget)
        self.a4.setGeometry(QtCore.QRect(380, 400, 68, 19))
        self.a4.setObjectName("a4")
        self.a5 = QtWidgets.QLabel(self.centralwidget)
        self.a5.setGeometry(QtCore.QRect(380, 430, 91, 20))
        self.a5.setObjectName("a5")
        BorrowForm1.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(BorrowForm1)
        self.statusbar.setObjectName("statusbar")
        BorrowForm1.setStatusBar(self.statusbar)

        self.l0.setDisabled(True)
        self.l1.setDisabled(True)
        self.l2.setDisabled(True)
        self.l3.setDisabled(True)
        self.l4.setDisabled(True)
        self.l5.setDisabled(True)
        
        self.bor
        self.a0.setText("Hello")
        
        self.cb0.stateChanged.connect(self.ch)
        self.cb1.stateChanged.connect(self.ch)
        self.cb2.stateChanged.connect(self.ch)
        self.cb3.stateChanged.connect(self.ch)
        self.cb4.stateChanged.connect(self.ch)
        self.cb5.stateChanged.connect(self.ch) 

        self.retranslateUi(BorrowForm1)
        QtCore.QMetaObject.connectSlotsByName(BorrowForm1)

    def retranslateUi(self, BorrowForm1):
        _translate = QtCore.QCoreApplication.translate
        BorrowForm1.setWindowTitle(_translate("BorrowForm1", "Borrow Equipment"))
        self.borrowbtn.setText(_translate("BorrowForm1", "Borrow"))
        self.label.setText(_translate("BorrowForm1", "QUANTITY"))
        self.label_7.setText(_translate("BorrowForm1", "CISCO BORROWING SYSTEM "))
        self.label_2.setText(_translate("BorrowForm1", "ITEM"))
        self.label_8.setText(_translate("BorrowForm1", "B O R R O W"))
        self.cb0.setText(_translate("BorrowForm1", "Rack"))
        self.cb1.setText(_translate("BorrowForm1", "Switch"))
        self.cb2.setText(_translate("BorrowForm1", "Router"))
        self.cb3.setText(_translate("BorrowForm1", "Console Cable"))
        self.cb4.setText(_translate("BorrowForm1", "LAN Cable"))
        self.cb5.setText(_translate("BorrowForm1", "Power Cable"))
        self.labelName.setText(_translate("BorrowForm1", "Name:"))
        self.labelStudNum.setText(_translate("BorrowForm1", "Student Number: "))
        self.labelSection.setText(_translate("BorrowForm1", "Section:"))
        self.labelRoom.setText(_translate("BorrowForm1", "Room:"))
        self.labelRoom_2.setText(_translate("BorrowForm1", "Professor:"))
        self.label_3.setText(_translate("BorrowForm1", "AVAILABLE"))
        self.a0.setText(_translate("BorrowForm1", "A1"))
        self.a1.setText(_translate("BorrowForm1", "A1"))
        self.a2.setText(_translate("BorrowForm1", "A1"))
        self.a3.setText(_translate("BorrowForm1", "A1"))
        self.a4.setText(_translate("BorrowForm1", "A1"))
        self.a5.setText(_translate("BorrowForm1", "A1"))
        
    
    def ch(self):
        if self.cb0.isChecked():
            self.l0.setDisabled(False)
        else:
            self.l0.setDisabled(True)
        
        if self.cb1.isChecked():
            self.l1.setDisabled(False)
        else:
            self.l1.setDisabled(True)
            
        if self.cb2.isChecked():
            self.l2.setDisabled(False)
        else:
            self.l2.setDisabled(True)
            
        if self.cb3.isChecked():
            self.l3.setDisabled(False)
        else:
            self.l3.setDisabled(True)
            
        if self.cb4.isChecked():
            self.l4.setDisabled(False)
        else:
            self.l4.setDisabled(True)
        
        if self.cb5.isChecked():
            self.l5.setDisabled(False)
        else:
            self.l5.setDisabled(True)

    def bor(self):
        conn = sqlite3.connect('StudentInfo.db')
        with conn:
            c = conn.cursor()
        c.execute("SELECT Available FROM eq")
        c.fetchall()
        for row in c:
            av0 = row[0]
            av1 = row[1]
            av2 = row[2]
            av3 = row[3]
            av4 = row[4]
            av5 = row[5]
            #self.a0.setText(row[0])
            #self.a1.setText(row[1])
            #self.a2.setText(row[2])
            #self.a3.setText(row[3])
            #self.a4.setText(row[4])
            #self.a5.setText(row[5])
        self.a0.setText(av0)
        self.a1.setText(av1)
        self.a2.setText(av2)
        self.a3.setText(av3)
        self.a4.setText(av4)
        self.a5.setText(av5)
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BorrowForm1 = QtWidgets.QMainWindow()
    ui = Ui_BorrowForm1()
    ui.setupUi(BorrowForm1)
    BorrowForm1.show()
    sys.exit(app.exec_())

