from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from Inventory import Inventory
from Student1 import Student
import sqlite3

class Ui_BackForm(object):
    foundctr = 0
    retctr = 0
    def setupUi(self, BackForm):
        BackForm.setObjectName("BackForm")
        BackForm.resize(800,600)
        BackForm.setEnabled(True)
        BackForm.setMinimumSize(QtCore.QSize(800, 600))
        BackForm.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(BackForm)
        self.centralwidget.setObjectName("centralwidget")
        self.Okbtn = QtWidgets.QPushButton(self.centralwidget)
        self.Okbtn.setGeometry(QtCore.QRect(620, 200, 61, 40))
        self.Okbtn.setText("")
        self.Okbtn.setFlat(True)
        self.Okbtn.setObjectName("Okbtn")
        
        self.Okbtn.setStyleSheet("QPushButton {background-image: url(button_ok.png) 0 0 0 0 stretch stretch; }")
        
        self.confirmbtn = QtWidgets.QPushButton(self.centralwidget)
        self.confirmbtn.setGeometry(QtCore.QRect(420, 490, 128, 40))
        self.confirmbtn.setText("")
        self.confirmbtn.setFlat(True)
        self.confirmbtn.setObjectName("confirmbtn")
        
        self.confirmbtn.setStyleSheet("QPushButton {background-image: url(button_confirm.png) 0 0 0 0 stretch stretch; }")
        
        self.labelStudNum = QtWidgets.QLabel(self.centralwidget)
        self.labelStudNum.setGeometry(QtCore.QRect(100, 160, 171, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelStudNum.setFont(font)
        self.labelStudNum.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelStudNum.setObjectName("labelStudNum")
        self.lineStudNum = QtWidgets.QLineEdit(self.centralwidget)
        self.lineStudNum.setGeometry(QtCore.QRect(280, 160, 411, 25))
        self.lineStudNum.setObjectName("lineStudNum")
        self.labelStudInfo = QtWidgets.QLabel(self.centralwidget)
        self.labelStudInfo.setGeometry(QtCore.QRect(30, 260, 271, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelStudInfo.setFont(font)
        self.labelStudInfo.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelStudInfo.setObjectName("labelStudInfo")
        self.labelName = QtWidgets.QLabel(self.centralwidget)
        self.labelName.setGeometry(QtCore.QRect(30, 300, 341, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.labelName.setFont(font)
        self.labelName.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelName.setObjectName("labelName")
        self.labelBorrowedEquipment = QtWidgets.QLabel(self.centralwidget)
        self.labelBorrowedEquipment.setGeometry(QtCore.QRect(440, 260, 291, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelBorrowedEquipment.setFont(font)
        self.labelBorrowedEquipment.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelBorrowedEquipment.setObjectName("labelBorrowedEquipment")
        self.labelCourse = QtWidgets.QLabel(self.centralwidget)
        self.labelCourse.setGeometry(QtCore.QRect(30, 330, 341, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.labelCourse.setFont(font)
        self.labelCourse.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelCourse.setObjectName("labelCourse")
        self.labeRoom = QtWidgets.QLabel(self.centralwidget)
        self.labeRoom.setGeometry(QtCore.QRect(30, 360, 341, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.labeRoom.setFont(font)
        self.labeRoom.setStyleSheet("color: rgb(255, 255, 255);")
        self.labeRoom.setObjectName("labeRoom")
        self.labelProfessor = QtWidgets.QLabel(self.centralwidget)
        self.labelProfessor.setGeometry(QtCore.QRect(30, 390, 341, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.labelProfessor.setFont(font)
        self.labelProfessor.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelProfessor.setObjectName("labelProfessor")
        self.labelRack = QtWidgets.QLabel(self.centralwidget)
        self.labelRack.setGeometry(QtCore.QRect(440, 290, 341, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.labelRack.setFont(font)
        self.labelRack.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelRack.setObjectName("labelRack")
        self.labelSwitch = QtWidgets.QLabel(self.centralwidget)
        self.labelSwitch.setGeometry(QtCore.QRect(440, 320, 341, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.labelSwitch.setFont(font)
        self.labelSwitch.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelSwitch.setObjectName("labelSwitch")
        self.labelRouter = QtWidgets.QLabel(self.centralwidget)
        self.labelRouter.setGeometry(QtCore.QRect(440, 350, 341, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.labelRouter.setFont(font)
        self.labelRouter.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelRouter.setObjectName("labelRouter")
        self.labelConsoleCable = QtWidgets.QLabel(self.centralwidget)
        self.labelConsoleCable.setGeometry(QtCore.QRect(440, 380, 341, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.labelConsoleCable.setFont(font)
        self.labelConsoleCable.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelConsoleCable.setObjectName("labelConsoleCable")
        self.lanelLanCable = QtWidgets.QLabel(self.centralwidget)
        self.lanelLanCable.setGeometry(QtCore.QRect(440, 410, 341, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lanelLanCable.setFont(font)
        self.lanelLanCable.setStyleSheet("color: rgb(255, 255, 255);")
        self.lanelLanCable.setObjectName("lanelLanCable")
        self.labelPowerCable = QtWidgets.QLabel(self.centralwidget)
        self.labelPowerCable.setGeometry(QtCore.QRect(440, 440, 341, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.labelPowerCable.setFont(font)
        self.labelPowerCable.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelPowerCable.setObjectName("labelPowerCable")
        self.clearbtn = QtWidgets.QPushButton(self.centralwidget)
        self.clearbtn.setGeometry(QtCore.QRect(290, 490, 95, 40))
        self.clearbtn.setText("")
        self.clearbtn.setFlat(True)
        self.clearbtn.setObjectName("clearbtn")
        
        self.clearbtn.setStyleSheet("QPushButton {background-image: url(button_clear.png) 0 0 0 0 stretch stretch; }")
        
        self.cancelbtn = QtWidgets.QPushButton(self.centralwidget)
        self.cancelbtn.setGeometry(QtCore.QRect(590, 490, 111, 40))
        self.cancelbtn.setText("")
        self.cancelbtn.setFlat(True)
        self.cancelbtn.setObjectName("cancelbtn")
        
        self.cancelbtn.setStyleSheet("QPushButton {background-image: url(button_cancel.png) 0 0 0 0 stretch stretch; }")
        
        BackForm.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(BackForm)
        self.statusbar.setObjectName("statusbar")
        BackForm.setStatusBar(self.statusbar)

        BackForm.setStyleSheet("#BackForm { background-image: url(Return.jpg) 0 0 0 0 stretch stretch; }")
        self.retranslateUi(BackForm)
        QtCore.QMetaObject.connectSlotsByName(BackForm)

        self.confirmbtn.setDisabled(True)
        self.lineStudNum.textChanged.connect(self.disableButton)

        self.Okbtn.clicked.connect(self.checkLineEdit)
        self.confirmbtn.clicked.connect(self.checkStudent)
        self.clearbtn.clicked.connect(self.clear)


    def retranslateUi(self, BackForm):
        _translate = QtCore.QCoreApplication.translate
        BackForm.setWindowTitle(_translate("BackForm", "Return Equipment"))
        self.labelStudNum.setText(_translate("BackForm", "Student Number:"))
        self.labelStudInfo.setText(_translate("BackForm", "STUDENT INFORMATION:"))
        self.labelName.setText(_translate("BackForm", "NAME:"))
        self.labelBorrowedEquipment.setText(_translate("BackForm", "BORROWED EQUIPMENT:"))
        self.labelCourse.setText(_translate("BackForm", "COURSE:"))
        self.labeRoom.setText(_translate("BackForm", "ROOM:"))
        self.labelProfessor.setText(_translate("BackForm", "PROFESSOR:"))
        self.labelRack.setText(_translate("BackForm", "RACK = "))
        self.labelSwitch.setText(_translate("BackForm", "SWITCH ="))
        self.labelRouter.setText(_translate("BackForm", "ROUTER ="))
        self.labelConsoleCable.setText(_translate("BackForm", "CONSOLE CABLE = "))
        self.lanelLanCable.setText(_translate("BackForm", "LAN CABLE ="))
        self.labelPowerCable.setText(_translate("BackForm", "POWER CABLE = "))

    def search(self):
        conn = sqlite3.connect('CiscoLab.db')
        with conn:
            c = conn.cursor()
        c.execute("SELECT * FROM StudentInfo WHERE StudentNumber=:sn", {'sn':self.lineStudNum.text()})
        info = c.fetchone()
        c.execute("SELECT * FROM Borrowed WHERE StudentNumber=:sn", {'sn':self.lineStudNum.text()})
        items = c.fetchone()
        if info is None:
            QMessageBox.about(self, "Warning", "Student not Found!")
            self.clear()
            self.lineStudNum.setText('')
            self.foundctr = 0
        else:
            
            self.labelName.setText("NAME: " + info[0])
            self.labelCourse.setText("COURSE: " + info[2])
            self.labeRoom.setText("ROOM: " + info[3])
            self.labelProfessor.setText("PROFESSOR: " + info[4])
            self.labelRack.setText("RACK = " + str(items[1]))
            self.labelSwitch.setText("SWITCH = " + str(items[2]))
            self.labelRouter.setText("ROUTER = " + str(items[3]))
            self.labelConsoleCable.setText("CONSOLE CABLE = " + str(items[4]))
            self.lanelLanCable.setText("LAN CABLE = " + str(items[5]))
            self.labelPowerCable.setText("POWER CABLE = " + str(items[6]))
            self.foundctr = 1
    
    def clear(self):
        self.lineStudNum.setText('')
        self.labelName.setText("NAME: ")
        self.labelCourse.setText("COURSE: ")
        self.labeRoom.setText("ROOM: ")
        self.labelProfessor.setText("PROFESSOR: ")
        self.labelRack.setText("RACK = ")
        self.labelSwitch.setText("SWITCH = ")
        self.labelRouter.setText("ROUTER = ")
        self.labelRouter.setText("CONSOLE CABLE = ")
        self.lanelLanCable.setText("LAN CABLE = ")
        self.labelPowerCable.setText("POWER CABLE = ")

    
    def checkLineEdit(self):
        if len(self.lineStudNum.text()) > 0:
            self.search()
        else:
            QMessageBox.about(self, "Warning", "Enter Student Number.")
    
    def checkStudent(self):
        if self.foundctr == 0:
            QMessageBox.about(self, "Warning", "Click OK Button.")
    
    def remove(self):
        st = self.lineStudNum.text()
        Student.removeStudInfo(st)
        Inventory.returnItems(st)
        self.clear()
        self.foundctr = 0
        QMessageBox.about(self, "Cisco Borrowing System", "Return Success!")
        
    def disableButton(self):
        if len(self.lineStudNum.text())>0:
            self.Okbtn.setDisabled(False)
            self.confirmbtn.setDisabled(False)
        else:
            self.Okbtn.setDisabled(True)
            self.confirmbtn.setDisabled(True)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BackForm = QtWidgets.QMainWindow()
    ui = Ui_BackForm()
    ui.setupUi(BackForm)
    BackForm.show()
    sys.exit(app.exec_())

